package com.evilgeniustechnologies.Wordrific.daomodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONFIGURATION.
 */
public class Configuration {

    private Long id;
    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private java.util.Date updatedAt;
    private String gameRules;
    private String base64EncodedPublicKey;
    private Integer correctAnswerEasy;
    private Integer correctAnswerMedium;
    private Integer correctAnswerHard;
    private Integer quickAnswerEasy;
    private Integer quickAnswerMedium;
    private Integer quickAnswerHard;
    private Integer timeForBonusEasy;
    private Integer timeForBonusMedium;
    private Integer timeForBonusHard;
    private Integer wrongAnswerEasy;
    private Integer wrongAnswerMedium;
    private Integer wrongAnswerHard;
    private Integer cluePenaltyEasy;
    private Integer cluePenaltyMedium;
    private Integer cluePenaltyHard;
    private Integer skipPuzzlePenalty;
    private Integer totalTime;
    private Integer totalPuzzles;

    public Configuration() {
    }

    public Configuration(Long id) {
        this.id = id;
    }

    public Configuration(Long id, String objectId, java.util.Date updatedAt, String gameRules, String base64EncodedPublicKey, Integer correctAnswerEasy, Integer correctAnswerMedium, Integer correctAnswerHard, Integer quickAnswerEasy, Integer quickAnswerMedium, Integer quickAnswerHard, Integer timeForBonusEasy, Integer timeForBonusMedium, Integer timeForBonusHard, Integer wrongAnswerEasy, Integer wrongAnswerMedium, Integer wrongAnswerHard, Integer cluePenaltyEasy, Integer cluePenaltyMedium, Integer cluePenaltyHard, Integer skipPuzzlePenalty, Integer totalTime, Integer totalPuzzles) {
        this.id = id;
        this.objectId = objectId;
        this.updatedAt = updatedAt;
        this.gameRules = gameRules;
        this.base64EncodedPublicKey = base64EncodedPublicKey;
        this.correctAnswerEasy = correctAnswerEasy;
        this.correctAnswerMedium = correctAnswerMedium;
        this.correctAnswerHard = correctAnswerHard;
        this.quickAnswerEasy = quickAnswerEasy;
        this.quickAnswerMedium = quickAnswerMedium;
        this.quickAnswerHard = quickAnswerHard;
        this.timeForBonusEasy = timeForBonusEasy;
        this.timeForBonusMedium = timeForBonusMedium;
        this.timeForBonusHard = timeForBonusHard;
        this.wrongAnswerEasy = wrongAnswerEasy;
        this.wrongAnswerMedium = wrongAnswerMedium;
        this.wrongAnswerHard = wrongAnswerHard;
        this.cluePenaltyEasy = cluePenaltyEasy;
        this.cluePenaltyMedium = cluePenaltyMedium;
        this.cluePenaltyHard = cluePenaltyHard;
        this.skipPuzzlePenalty = skipPuzzlePenalty;
        this.totalTime = totalTime;
        this.totalPuzzles = totalPuzzles;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public String getGameRules() {
        return gameRules;
    }

    public void setGameRules(String gameRules) {
        this.gameRules = gameRules;
    }

    public String getBase64EncodedPublicKey() {
        return base64EncodedPublicKey;
    }

    public void setBase64EncodedPublicKey(String base64EncodedPublicKey) {
        this.base64EncodedPublicKey = base64EncodedPublicKey;
    }

    public Integer getCorrectAnswerEasy() {
        return correctAnswerEasy;
    }

    public void setCorrectAnswerEasy(Integer correctAnswerEasy) {
        this.correctAnswerEasy = correctAnswerEasy;
    }

    public Integer getCorrectAnswerMedium() {
        return correctAnswerMedium;
    }

    public void setCorrectAnswerMedium(Integer correctAnswerMedium) {
        this.correctAnswerMedium = correctAnswerMedium;
    }

    public Integer getCorrectAnswerHard() {
        return correctAnswerHard;
    }

    public void setCorrectAnswerHard(Integer correctAnswerHard) {
        this.correctAnswerHard = correctAnswerHard;
    }

    public Integer getQuickAnswerEasy() {
        return quickAnswerEasy;
    }

    public void setQuickAnswerEasy(Integer quickAnswerEasy) {
        this.quickAnswerEasy = quickAnswerEasy;
    }

    public Integer getQuickAnswerMedium() {
        return quickAnswerMedium;
    }

    public void setQuickAnswerMedium(Integer quickAnswerMedium) {
        this.quickAnswerMedium = quickAnswerMedium;
    }

    public Integer getQuickAnswerHard() {
        return quickAnswerHard;
    }

    public void setQuickAnswerHard(Integer quickAnswerHard) {
        this.quickAnswerHard = quickAnswerHard;
    }

    public Integer getTimeForBonusEasy() {
        return timeForBonusEasy;
    }

    public void setTimeForBonusEasy(Integer timeForBonusEasy) {
        this.timeForBonusEasy = timeForBonusEasy;
    }

    public Integer getTimeForBonusMedium() {
        return timeForBonusMedium;
    }

    public void setTimeForBonusMedium(Integer timeForBonusMedium) {
        this.timeForBonusMedium = timeForBonusMedium;
    }

    public Integer getTimeForBonusHard() {
        return timeForBonusHard;
    }

    public void setTimeForBonusHard(Integer timeForBonusHard) {
        this.timeForBonusHard = timeForBonusHard;
    }

    public Integer getWrongAnswerEasy() {
        return wrongAnswerEasy;
    }

    public void setWrongAnswerEasy(Integer wrongAnswerEasy) {
        this.wrongAnswerEasy = wrongAnswerEasy;
    }

    public Integer getWrongAnswerMedium() {
        return wrongAnswerMedium;
    }

    public void setWrongAnswerMedium(Integer wrongAnswerMedium) {
        this.wrongAnswerMedium = wrongAnswerMedium;
    }

    public Integer getWrongAnswerHard() {
        return wrongAnswerHard;
    }

    public void setWrongAnswerHard(Integer wrongAnswerHard) {
        this.wrongAnswerHard = wrongAnswerHard;
    }

    public Integer getCluePenaltyEasy() {
        return cluePenaltyEasy;
    }

    public void setCluePenaltyEasy(Integer cluePenaltyEasy) {
        this.cluePenaltyEasy = cluePenaltyEasy;
    }

    public Integer getCluePenaltyMedium() {
        return cluePenaltyMedium;
    }

    public void setCluePenaltyMedium(Integer cluePenaltyMedium) {
        this.cluePenaltyMedium = cluePenaltyMedium;
    }

    public Integer getCluePenaltyHard() {
        return cluePenaltyHard;
    }

    public void setCluePenaltyHard(Integer cluePenaltyHard) {
        this.cluePenaltyHard = cluePenaltyHard;
    }

    public Integer getSkipPuzzlePenalty() {
        return skipPuzzlePenalty;
    }

    public void setSkipPuzzlePenalty(Integer skipPuzzlePenalty) {
        this.skipPuzzlePenalty = skipPuzzlePenalty;
    }

    public Integer getTotalTime() {
        return totalTime;
    }

    public void setTotalTime(Integer totalTime) {
        this.totalTime = totalTime;
    }

    public Integer getTotalPuzzles() {
        return totalPuzzles;
    }

    public void setTotalPuzzles(Integer totalPuzzles) {
        this.totalPuzzles = totalPuzzles;
    }

}
