package com.evilgeniustechnologies.Wordrific.daomodel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig friendshipDaoConfig;
    private final DaoConfig configurationDaoConfig;
    private final DaoConfig puzzleDaoConfig;
    private final DaoConfig scoreDaoConfig;

    private final UserDao userDao;
    private final FriendshipDao friendshipDao;
    private final ConfigurationDao configurationDao;
    private final PuzzleDao puzzleDao;
    private final ScoreDao scoreDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        friendshipDaoConfig = daoConfigMap.get(FriendshipDao.class).clone();
        friendshipDaoConfig.initIdentityScope(type);

        configurationDaoConfig = daoConfigMap.get(ConfigurationDao.class).clone();
        configurationDaoConfig.initIdentityScope(type);

        puzzleDaoConfig = daoConfigMap.get(PuzzleDao.class).clone();
        puzzleDaoConfig.initIdentityScope(type);

        scoreDaoConfig = daoConfigMap.get(ScoreDao.class).clone();
        scoreDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        friendshipDao = new FriendshipDao(friendshipDaoConfig, this);
        configurationDao = new ConfigurationDao(configurationDaoConfig, this);
        puzzleDao = new PuzzleDao(puzzleDaoConfig, this);
        scoreDao = new ScoreDao(scoreDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Friendship.class, friendshipDao);
        registerDao(Configuration.class, configurationDao);
        registerDao(Puzzle.class, puzzleDao);
        registerDao(Score.class, scoreDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        friendshipDaoConfig.getIdentityScope().clear();
        configurationDaoConfig.getIdentityScope().clear();
        puzzleDaoConfig.getIdentityScope().clear();
        scoreDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FriendshipDao getFriendshipDao() {
        return friendshipDao;
    }

    public ConfigurationDao getConfigurationDao() {
        return configurationDao;
    }

    public PuzzleDao getPuzzleDao() {
        return puzzleDao;
    }

    public ScoreDao getScoreDao() {
        return scoreDao;
    }

}
