package com.evilgeniustechnologies.Wordrific.daomodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PUZZLE.
 */
public class Puzzle {

    private Long id;
    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private java.util.Date updatedAt;
    private Integer number;
    private Integer set;
    private byte[] image;
    private String answer;
    private String clues;
    private String bonusClue;
    private Integer difficulty;

    public Puzzle() {
    }

    public Puzzle(Long id) {
        this.id = id;
    }

    public Puzzle(Long id, String objectId, java.util.Date updatedAt, Integer number, Integer set, byte[] image, String answer, String clues, String bonusClue, Integer difficulty) {
        this.id = id;
        this.objectId = objectId;
        this.updatedAt = updatedAt;
        this.number = number;
        this.set = set;
        this.image = image;
        this.answer = answer;
        this.clues = clues;
        this.bonusClue = bonusClue;
        this.difficulty = difficulty;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer number) {
        this.number = number;
    }

    public Integer getSet() {
        return set;
    }

    public void setSet(Integer set) {
        this.set = set;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getClues() {
        return clues;
    }

    public void setClues(String clues) {
        this.clues = clues;
    }

    public String getBonusClue() {
        return bonusClue;
    }

    public void setBonusClue(String bonusClue) {
        this.bonusClue = bonusClue;
    }

    public Integer getDifficulty() {
        return difficulty;
    }

    public void setDifficulty(Integer difficulty) {
        this.difficulty = difficulty;
    }

}
