package com.evilgeniustechnologies.Wordrific.daomodel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCORE.
 */
public class Score {

    private Long id;
    /** Not-null value. */
    private String objectId;
    /** Not-null value. */
    private java.util.Date updatedAt;
    private Integer set;
    private Integer score;
    private Integer elapsedTime;
    /** Not-null value. */
    private String userObjectId;
    private Long userId;

    public Score() {
    }

    public Score(Long id) {
        this.id = id;
    }

    public Score(Long id, String objectId, java.util.Date updatedAt, Integer set, Integer score, Integer elapsedTime, String userObjectId, Long userId) {
        this.id = id;
        this.objectId = objectId;
        this.updatedAt = updatedAt;
        this.set = set;
        this.score = score;
        this.elapsedTime = elapsedTime;
        this.userObjectId = userObjectId;
        this.userId = userId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getObjectId() {
        return objectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Integer getSet() {
        return set;
    }

    public void setSet(Integer set) {
        this.set = set;
    }

    public Integer getScore() {
        return score;
    }

    public void setScore(Integer score) {
        this.score = score;
    }

    public Integer getElapsedTime() {
        return elapsedTime;
    }

    public void setElapsedTime(Integer elapsedTime) {
        this.elapsedTime = elapsedTime;
    }

    /** Not-null value. */
    public String getUserObjectId() {
        return userObjectId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserObjectId(String userObjectId) {
        this.userObjectId = userObjectId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

}
